version: '3'
services:
        neo4j:
                image: neo4j:4.2.1
                container_name: neo4j
                ports:
                        - 7474:7474
                        - 7687:7687
                environment:
                        NEO4J_AUTH: 'neo4j/a123456+'
        
        elasticsearch:
                image: elasticsearch:7.10.1
                container_name: elasticsearch
                ports:
                        - 9200:9200
                environment:
                        - xpack.security.enabled=false
                        - discovery.type=single-node
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
                        nofile:
                                soft: 65536
                                hard: 65536
                         
        kibana:                
                image: kibana:7.10.1
                container_name: kibana
                environment:
                        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
                ports:
                        - 5601:5601
                depends_on:
                        - elasticsearch
        kazdream:
                image: kazdream
                container_name: kazdream
                ports:
                        - 5055:5050
